#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")


    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # store username
    usr = sys.argv[1]
    
    # get list of tweets
    tweets = helpers.get_user_timeline(screen_name=usr.lstrip("@"), count=50)
    
    # check that tweets were received
    if tweets == None:
        sys.exit("Unable to retrieve tweets")
    
    # iterate over each tweet
    for i in range(len(tweets)):

        # calculate positivity score using analyzer
        score = analyzer.analyze(tweets[i])
        
        # print out the tweet by colour based on score
        if score > 0.0:
            print(colored("{} {}, {}".format(score, tweets[i], sys.argv[1]), "green"))
        elif score < 0.0:
            print(colored("{} {}, {}".format(score, tweets[i], sys.argv[1]), "red"))
        else:
            print(colored("{} {}, {}".format(score, tweets[i], sys.argv[1]), "yellow"))

if __name__ == "__main__":
    main()